import type { Product } from "./types";

export const products: Product[] = [
  {
    id: "1",
    slug: "10-pack-alibarbar-ingot-9000-puffs",
    name: "10 PACK – ALIBARBAR INGOT – 9000 PUFFS",
    category: "ALIBARBAR 9000",
    brand: "ALIBARBAR",
    price: 439.5,
    compareAtPrice: 890,
    image: "/products/alibarbar-10.svg",
    imageTone: "#1a1a2e",
    description:
      "You can request flavours at checkout in the order notes section. All flavours are in stock. Alibarbar Ingot — up to 9000 puffs, 22ml e-liquid, 2350mAh battery, LED display.",
    puffs: 9000,
    onSale: true,
    featured: true,
  },
  {
    id: "2",
    slug: "20-pack-alibarbar-ingot-9000-puffs",
    name: "20 PACK – ALIBARBAR INGOT – 9000 PUFFS",
    category: "ALIBARBAR 9000",
    brand: "ALIBARBAR",
    price: 879,
    compareAtPrice: 1780,
    image: "/products/alibarbar-20.svg",
    imageTone: "#16213e",
    description: "Bulk 20-pack Alibarbar Ingot disposable vapes — 9000 puffs each.",
    puffs: 9000,
    onSale: true,
    featured: true,
  },
  {
    id: "3",
    slug: "3-pack-alibarbar-ingot-9000-puffs",
    name: "3 PACK – ALIBARBAR INGOT – 9000 PUFFS",
    category: "ALIBARBAR 9000",
    brand: "ALIBARBAR",
    price: 131.85,
    compareAtPrice: 267,
    image: "/products/alibarbar-3.svg",
    imageTone: "#0f3460",
    description: "3-pack Alibarbar Ingot disposable vapes — 9000 puffs each.",
    puffs: 9000,
    onSale: true,
    featured: true,
  },
  {
    id: "4",
    slug: "5-pack-alibarbar-ingot-9000-puffs",
    name: "5 PACK – ALIBARBAR INGOT – 9000 PUFFS",
    category: "ALIBARBAR 9000",
    brand: "ALIBARBAR",
    price: 219.75,
    compareAtPrice: 445,
    image: "/products/alibarbar-5.svg",
    imageTone: "#533483",
    description: "5-pack Alibarbar Ingot disposable vapes — 9000 puffs each.",
    puffs: 9000,
    onSale: true,
    featured: true,
  },
  {
    id: "5",
    slug: "banana-buzz-alibarbar-ingot-9000-puffs",
    name: "BANANA BUZZ – ALIBARBAR INGOT – 9000 PUFFS",
    category: "ALIBARBAR 9000",
    brand: "ALIBARBAR",
    price: 43.95,
    compareAtPrice: 89,
    image: "/products/banana-buzz.svg",
    imageTone: "#f4d03f",
    description: "Banana Buzz flavour Alibarbar Ingot — smooth banana with a sweet finish.",
    puffs: 9000,
    onSale: true,
    featured: true,
  },
  {
    id: "6",
    slug: "blackberry-ice-alibarbar-ingot-9000-puffs",
    name: "BLACKBERRY ICE – ALIBARBAR INGOT – 9000 PUFFS",
    category: "ALIBARBAR 9000",
    brand: "ALIBARBAR",
    price: 43.95,
    compareAtPrice: 89,
    image: "/products/blackberry-ice.svg",
    imageTone: "#4a235a",
    description: "Blackberry Ice Alibarbar Ingot — juicy blackberry cooled with menthol.",
    puffs: 9000,
    onSale: true,
    featured: true,
  },
  {
    id: "7",
    slug: "blackberry-pomegranate-cherry-alibarbar-ingot-9000-puffs",
    name: "BLACKBERRY POMEGRANATE CHERRY – ALIBARBAR INGOT – 9000 PUFFS",
    category: "ALIBARBAR 9000",
    brand: "ALIBARBAR",
    price: 43.95,
    compareAtPrice: 89,
    image: "/products/bpc.svg",
    imageTone: "#922b21",
    description: "Triple fruit blend — blackberry, pomegranate and cherry.",
    puffs: 9000,
    onSale: true,
    featured: true,
  },
  {
    id: "8",
    slug: "waka-smash-green-grape-6000-puffs",
    name: "WAKA SMASH GREEN GRAPE – 6000 PUFFS",
    category: "WAKA SMASH 6000",
    brand: "WAKA",
    price: 30,
    compareAtPrice: 50,
    image: "/products/waka-grape.svg",
    imageTone: "#27ae60",
    description: "Waka Smash Green Grape — crisp green grape, 6000 puffs.",
    puffs: 6000,
    onSale: true,
    bestSeller: true,
  },
  {
    id: "9",
    slug: "waka-smash-mango-orange-6000-puffs",
    name: "WAKA SMASH MANGO ORANGE – 6000 PUFFS",
    category: "WAKA SMASH 6000",
    brand: "WAKA",
    price: 30,
    compareAtPrice: 50,
    image: "/products/waka-mango.svg",
    imageTone: "#e67e22",
    description: "Waka Smash Mango Orange — tropical mango and citrus.",
    puffs: 6000,
    onSale: true,
    bestSeller: true,
  },
  {
    id: "10",
    slug: "waka-smash-guava-zest-6000-puffs",
    name: "WAKA SMASH GUAVA ZEST – 6000 PUFFS",
    category: "WAKA SMASH 6000",
    brand: "WAKA",
    price: 30,
    compareAtPrice: 50,
    image: "/products/waka-guava.svg",
    imageTone: "#e74c3c",
    description: "Waka Smash Guava Zest — bright guava with citrus zest.",
    puffs: 6000,
    onSale: true,
    bestSeller: true,
  },
  {
    id: "11",
    slug: "waka-smash-juicy-black-currant-6000-puffs",
    name: "WAKA SMASH JUICY BLACK CURRANT – 6000 PUFFS",
    category: "WAKA SMASH 6000",
    brand: "WAKA",
    price: 30,
    compareAtPrice: 50,
    image: "/products/waka-currant.svg",
    imageTone: "#6c3483",
    description: "Waka Smash Juicy Black Currant — rich berry intensity.",
    puffs: 6000,
    onSale: true,
    bestSeller: true,
  },
  {
    id: "12",
    slug: "waka-smash-peach-kiwi-melon-6000-puffs",
    name: "WAKA SMASH PEACH KIWI MELON – 6000 PUFFS",
    category: "WAKA SMASH 6000",
    brand: "WAKA",
    price: 30,
    compareAtPrice: 50,
    image: "/products/waka-peach.svg",
    imageTone: "#f5b041",
    description: "Waka Smash Peach Kiwi Melon — sweet summer fruit mix.",
    puffs: 6000,
    onSale: true,
    bestSeller: true,
  },
  {
    id: "13",
    slug: "waka-smash-pear-sparkle-6000-puffs",
    name: "WAKA SMASH PEAR SPARKLE – 6000 PUFFS",
    category: "WAKA SMASH 6000",
    brand: "WAKA",
    price: 30,
    compareAtPrice: 50,
    image: "/products/waka-pear.svg",
    imageTone: "#58d68d",
    description: "Waka Smash Pear Sparkle — crisp pear with a sparkling finish.",
    puffs: 6000,
    onSale: true,
    bestSeller: true,
  },
  {
    id: "14",
    slug: "waka-smash-pineapple-melon-6000-puffs",
    name: "WAKA SMASH PINEAPPLE MELON – 6000 PUFFS",
    category: "WAKA SMASH 6000",
    brand: "WAKA",
    price: 30,
    compareAtPrice: 50,
    image: "/products/waka-pineapple.svg",
    imageTone: "#f4d03f",
    description: "Waka Smash Pineapple Melon — tropical pineapple and melon.",
    puffs: 6000,
    onSale: true,
    bestSeller: true,
  },
  {
    id: "15",
    slug: "waka-smash-pomegranate-pop-6000-puffs",
    name: "WAKA SMASH POMEGRANATE POP – 6000 PUFFS",
    category: "WAKA SMASH 6000",
    brand: "WAKA",
    price: 30,
    compareAtPrice: 50,
    image: "/products/waka-pomegranate.svg",
    imageTone: "#c0392b",
    description: "Waka Smash Pomegranate Pop — tart pomegranate burst.",
    puffs: 6000,
    onSale: true,
    bestSeller: true,
  },
  {
    id: "16",
    slug: "10-pack-iget-bar-pro-10000-puffs",
    name: "10 PACK – IGET BAR PRO – 10000 PUFFS",
    category: "IGET BAR PRO 10000",
    brand: "IGET",
    price: 439.5,
    compareAtPrice: 990,
    image: "/products/iget-10.svg",
    imageTone: "#1c2833",
    description: "10-pack IGET Bar Pro — up to 10000 puffs each.",
    puffs: 10000,
    onSale: true,
  },
  {
    id: "17",
    slug: "20-pack-iget-bar-pro-10000-puffs",
    name: "20 PACK – IGET BAR PRO – 10000 PUFFS",
    category: "IGET BAR PRO 10000",
    brand: "IGET",
    price: 879,
    compareAtPrice: 1980,
    image: "/products/iget-20.svg",
    imageTone: "#212f3d",
    description: "20-pack IGET Bar Pro — up to 10000 puffs each.",
    puffs: 10000,
    onSale: true,
  },
  {
    id: "18",
    slug: "3-pack-iget-bar-pro-10000-puffs",
    name: "3 PACK – IGET BAR PRO – 10000 PUFFS",
    category: "IGET BAR PRO 10000",
    brand: "IGET",
    price: 131.85,
    compareAtPrice: 297,
    image: "/products/iget-3.svg",
    imageTone: "#2c3e50",
    description: "3-pack IGET Bar Pro — up to 10000 puffs each.",
    puffs: 10000,
    onSale: true,
  },
  {
    id: "19",
    slug: "5-pack-iget-bar-pro-10000-puffs",
    name: "5 PACK – IGET BAR PRO – 10000 PUFFS",
    category: "IGET BAR PRO 10000",
    brand: "IGET",
    price: 219.75,
    compareAtPrice: 495,
    image: "/products/iget-5.svg",
    imageTone: "#34495e",
    description: "5-pack IGET Bar Pro — up to 10000 puffs each.",
    puffs: 10000,
    onSale: true,
  },
  {
    id: "20",
    slug: "blackberry-ice-iget-bar-pro-10000-puffs",
    name: "BLACKBERRY ICE – IGET BAR PRO – 10000 PUFFS",
    category: "IGET BAR PRO 10000",
    brand: "IGET",
    price: 43.95,
    compareAtPrice: 99,
    image: "/products/iget-blackberry.svg",
    imageTone: "#5b2c6f",
    description: "IGET Bar Pro Blackberry Ice — cool berry flavour, 10000 puffs.",
    puffs: 10000,
    onSale: true,
  },
  {
    id: "21",
    slug: "alfakher-crown-bar-8000-10-pack",
    name: "ALFAKHER CROWN BAR – 8000 PUFFS – 10 PACK",
    category: "ALFAKHER CROWN BAR 8000",
    brand: "ALFAKHER",
    price: 409,
    compareAtPrice: 650,
    image: "/products/alfakher-10.svg",
    imageTone: "#7d3c98",
    description: "10-pack Al Fakher Crown Bar — premium shisha-inspired flavours.",
    puffs: 8000,
    onSale: true,
  },
  {
    id: "22",
    slug: "alfakher-crown-bar-berry-ice-8000",
    name: "ALFAKHER CROWN BAR BERRY ICE – 8000 PUFFS",
    category: "ALFAKHER CROWN BAR 8000",
    brand: "ALFAKHER",
    price: 44,
    compareAtPrice: 65,
    image: "/products/alfakher-berry.svg",
    imageTone: "#8e44ad",
    description: "Al Fakher Crown Bar Berry Ice — classic berry with ice.",
    puffs: 8000,
    onSale: true,
  },
  {
    id: "23",
    slug: "hqd-slick-6000-10-pack",
    name: "10 PACK – HQD SLICK – 6000 PUFFS",
    category: "HQD SLICK 6000",
    brand: "HQD",
    price: 139.5,
    compareAtPrice: 590,
    image: "/products/hqd-10.svg",
    imageTone: "#1a5276",
    description: "10-pack HQD Slick — ready to use, bold flavours.",
    puffs: 6000,
    onSale: true,
  },
  {
    id: "24",
    slug: "hqd-slick-black-ice-6000",
    name: "HQD SLICK BLACK ICE – 6000 PUFFS",
    category: "HQD SLICK 6000",
    brand: "HQD",
    price: 15.95,
    compareAtPrice: 59,
    image: "/products/hqd-black-ice.svg",
    imageTone: "#1c2833",
    description: "HQD Slick Black Ice — icy cool menthol.",
    puffs: 6000,
    onSale: true,
  },
  {
    id: "25",
    slug: "hqd-slick-blueberry-lemonade-6000",
    name: "HQD SLICK BLUEBERRY LEMONADE – 6000 PUFFS",
    category: "HQD SLICK 6000",
    brand: "HQD",
    price: 11.95,
    compareAtPrice: 59,
    image: "/products/hqd-blueberry.svg",
    imageTone: "#3498db",
    description: "HQD Slick Blueberry Lemonade — tart lemonade with blueberry.",
    puffs: 6000,
    onSale: true,
  },
  {
    id: "26",
    slug: "gunnpod-plus-4500-10-pack",
    name: "GUNNPOD PLUS – 4500 PUFFS – 10 PACK",
    category: "GUNNPOD PLUS 4500",
    brand: "GUNNPOD",
    price: 259,
    compareAtPrice: 480,
    image: "/products/gunnpod-10.svg",
    imageTone: "#117a65",
    description: "10-pack GunnPod Plus — sleek portable disposable vapes.",
    puffs: 4500,
    onSale: true,
  },
  {
    id: "27",
    slug: "gunnpod-plus-cherry-pomegranate-ice-4500",
    name: "GUNNPOD PLUS CHERRY POMEGRANATE ICE – 4500 PUFFS",
    category: "GUNNPOD PLUS 4500",
    brand: "GUNNPOD",
    price: 29,
    compareAtPrice: 48,
    image: "/products/gunnpod-cherry.svg",
    imageTone: "#922b21",
    description: "GunnPod Plus Cherry Pomegranate Ice.",
    puffs: 4500,
    onSale: true,
  },
  {
    id: "28",
    slug: "gunnpod-plus-classic-tobacco-4500",
    name: "GUNNPOD PLUS CLASSIC TOBACCO – 4500 PUFFS",
    category: "GUNNPOD PLUS 4500",
    brand: "GUNNPOD",
    price: 29,
    compareAtPrice: 48,
    image: "/products/gunnpod-tobacco.svg",
    imageTone: "#6e2c00",
    description: "GunnPod Plus Classic Tobacco.",
    puffs: 4500,
    onSale: true,
  },
  {
    id: "29",
    slug: "mr-fog-max-air-3600-10-pack",
    name: "MR FOG MAX AIR – 3600 PUFFS – 10 PACK",
    category: "MR FOG 3600",
    brand: "MR FOG",
    price: 259,
    compareAtPrice: 450,
    image: "/products/mrfog-10.svg",
    imageTone: "#1b4f72",
    description: "10-pack Mr Fog Max Air — smooth, flavourful disposable vapes.",
    puffs: 3600,
    onSale: true,
  },
  {
    id: "30",
    slug: "mr-fog-max-air-3600-3-pack",
    name: "MR FOG MAX AIR – 3600 PUFFS – 3 PACK",
    category: "MR FOG 3600",
    brand: "MR FOG",
    price: 83,
    compareAtPrice: 135,
    image: "/products/mrfog-3.svg",
    imageTone: "#2874a6",
    description: "3-pack Mr Fog Max Air.",
    puffs: 3600,
    onSale: true,
  },
];

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug);
}

export function getFeaturedProducts() {
  return products.filter((p) => p.featured);
}

export function getBestSellers() {
  return products.filter((p) => p.bestSeller);
}

export function getProductsByBrand(brand: string) {
  return products.filter(
    (p) => p.brand.toLowerCase() === brand.toLowerCase(),
  );
}

export function formatPrice(amount: number) {
  return new Intl.NumberFormat("en-AU", {
    style: "currency",
    currency: "AUD",
  }).format(amount);
}

export const faqs = [
  {
    q: "What products do you sell?",
    a: "We sell disposable vapes, vape kits, vape pods, e-liquids, vape coils, and vape devices online in Australia.",
  },
  {
    q: "Can I buy vapes online in Australia?",
    a: "Yes, you can buy vapes online Australia through our store with a simple and hassle-free process.",
  },
  {
    q: "Do you deliver vapes across Australia?",
    a: "Yes, we offer fast and reliable vape delivery Australia-wide.",
  },
  {
    q: "Are your vape products authentic?",
    a: "All our vape products are sourced from reputable brands and regulated suppliers.",
  },
  {
    q: "Do you sell nicotine vapes?",
    a: "Yes, we offer nicotine vape products in compliance with Australian regulations.",
  },
  {
    q: "Are your vapes suitable for beginners?",
    a: "Yes, we stock easy-to-use disposable vapes and starter vape kits ideal for beginners.",
  },
  {
    q: "How long does delivery take?",
    a: "Delivery times vary by location, but most orders arrive within a few business days.",
  },
  {
    q: "Do you offer customer support?",
    a: "Yes, our support team is available to help with orders, products, and general enquiries.",
  },
];

export const navLinks = [
  { href: "/", label: "Home" },
  { href: "/shop", label: "Shop All" },
  { href: "/about", label: "About" },
  { href: "/contact", label: "Contact" },
  { href: "/account", label: "My account" },
  { href: "/cart", label: "Cart" },
];

export const footerLinks = [
  { href: "/refund-policy", label: "Refund Policy" },
  { href: "/terms", label: "Terms & Conditions" },
  { href: "/faq", label: "FAQ" },
  { href: "/privacy", label: "Privacy Policy" },
];
